name: Manual Register to ModParks

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            core.setOutput("tag", latest.data.tag_name);
            core.setOutput("name", latest.data.assets[0].name);
            core.setOutput("body", latest.data.body || "");

      - name: Register to ModParks
        env:
          MODPARKS_URL: "https://modparks.pitan76.net"
          PROJECT_SLUG: "little-intermediary-fallback"
        run: |
          TAG="${{ steps.release.outputs.tag }}"
          FILE_NAME="${{ steps.release.outputs.name }}"
          FILE_URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/${FILE_NAME}"

          curl -X POST "$MODPARKS_URL/api/v1/projects/$PROJECT_SLUG/versions" \
            -H "Authorization: Bearer ${{ secrets.MODPARKS_API_KEY }}" \
            -F "versionNumber=$TAG" \
            -F "mcVersions=26.1" \
            -F "mcVersions=26.1.1" \
            -F "mcVersions=26.1.2" \
            -F "loaders=fabric" \
            -F "changelog=${{ steps.release.outputs.body }}" \
            -F "fileUrl=$FILE_URL"